# Generated by Django 5.0.6 on 2024-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('english', 'English')], max_length=50)),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
